# Generated by Django 4.1.1 on 2022-10-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('author', models.CharField(default='', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=255)),
                ('handle', models.CharField(default='', max_length=255)),
                ('role', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.user')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
