# Generated by Django 4.1.1 on 2022-09-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='polls_book',
        ),
    ]
