# Generated by Django 4.1.1 on 2022-11-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_user_login'),
        ('crud', '0004_user'),
    ]

    operations = [
    ]
